spring.application.name=webapi

# Database Configuration
spring.datasource.url=jdbc:sqlserver://proyectola.database.windows.net;databaseName=proyectola;encrypt=true;trustServerCertificate=true
spring.datasource.username=lindsay
spring.datasource.password=LvL262002
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Python Service
python.service.url=https://tesis-ia-service-production.up.railway.app

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=coders.elin@gmail.com
spring.mail.password=ozlq wevf gdar lawj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
